[package]
product-name = "ipmap"
version = "0.3.0"

[build]
beforeDevCommand = "npm run dev"
beforeBuildCommand = "npm run build"
devPath = "http://localhost:5173"
distDir = "src-web/build"

[tauri.allowlist]
all = false
shell = { open = true }
window = { center = true }
dialog = { message = true }

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = "2023 Grant Handy"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "com.grantshandy.dev"
targets = "all"
deb = { depends = ["libpcap0.8"] }

[tauri.updater]
active = false

[tauri]
windows = [
 { label = "ipmap", title = "ipmap" }
]
