[package]
name = "ipmap-child"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
ip_rfc.workspace = true
child-ipc = { path = "../child-ipc", features = ["child"] }
pcap-dyn = { path = "../pcap-dyn" }
trippy-core = "0.13.0"
trippy-privilege = "0.13.0"
