
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openAboutWindow() : Promise<void> {
    await TAURI_INVOKE("open_about_window");
},
async initCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async download(source: BuiltinDatabaseSources, stage: TAURI_CHANNEL<string>, progress: TAURI_CHANNEL<number>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download", { source, stage, progress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async databaseInfo() : Promise<DatabaseStoreInfo> {
    return await TAURI_INVOKE("database_info");
},
async setSelected(name: string) : Promise<void> {
    await TAURI_INVOKE("set_selected", { name });
},
async lookupIp(ip: string) : Promise<LookupInfo | null> {
    return await TAURI_INVOKE("lookup_ip", { ip });
},
/**
 * Get a hostname with the system for a given IP address.
 */
async lookupHost(host: string) : Promise<Result<string | null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_host", { host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a hostname with the system for a given IP address.
 */
async lookupDns(ip: string) : Promise<Result<string | null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_dns", { ip }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
databaseStoreInfo: DatabaseStoreInfo
}>({
databaseStoreInfo: "database-store-info"
})

/** user-defined constants **/

export const APP_VERSION = "5.0.0" as const;
export const PLATFORM = "linux" as const;
export const PCAP_ERROR_KINDS = ["UnexpectedType","TerminatedUnexpectedly","ChildTimeout","Ipc","InsufficientPermissions","LibLoading","Runtime","ChildNotFound","EstablishConnection","Io"] as const;

/** user-defined types **/

export type BuiltinDatabaseSources = "dbip" | "geolite2"
/**
 * A basic latitude/longitude pair.
 */
export type Coordinate = { 
/**
 * Latitude
 */
lat: number; 
/**
 * Longitude
 */
lng: number }
export type DatabaseStoreInfo = { loaded: string[]; selected: string | null; loading: boolean }
/**
 * A [`Coordinate`]'s associated city, region, and country.
 */
export type Location = { city: string | null; region: string | null; countryCode: string }
/**
 * A [`Coordinate`]/[`Location`] pair.
 */
export type LookupInfo = { crd: Coordinate; loc: Location }
export type TAURI_CHANNEL<TSend> = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
