
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Load a IP-Geolocation database into the program from the filename.
 */
async loadDatabase(path: string, err: TAURI_CHANNEL<string>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_database", { path, err }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unload the database, freeing up memory.
 */
async unloadDatabase(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_database", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve the current state of the database.
 * This info is given out in [`DbStateChange`], but this is useful for getting it at page load, for example.
 */
async databaseState() : Promise<DbStateInfo> {
    return await TAURI_INVOKE("database_state");
},
/**
 * Set the given database as the selected database for lookups.
 */
async setSelectedDatabase(path: string) : Promise<void> {
    await TAURI_INVOKE("set_selected_database", { path });
},
/**
 * Lookup a given IP address in the currently selected database(s).
 */
async lookupIp(ip: string) : Promise<LookupInfo | null> {
    return await TAURI_INVOKE("lookup_ip", { ip });
},
async syncPcapState() : Promise<Result<PcapStateInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_pcap_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCapture(device: Device, channel: TAURI_CHANNEL<ActiveConnections>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture", { device, channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dbStateChange: DbStateChange,
pcapStateChange: PcapStateChange
}>({
dbStateChange: "db-state-change",
pcapStateChange: "pcap-state-change"
})

/** user-defined constants **/



/** user-defined types **/

export type ActiveConnections = { data: Partial<{ [key in string]: ConnectionInfo }> }
export type ConnectionInfo = { up: MovingAverageInfo; down: MovingAverageInfo }
/**
 * A latitude/longitude coordinate.
 */
export type Coordinate = { lat: number; lng: number }
export type DbCollectionInfo = { loaded: string[]; selected: string | null }
/**
 * Fired any time the state of loaded or selected databases are changed on the backend.
 */
export type DbStateChange = DbStateInfo
export type DbStateInfo = { ipv4: DbCollectionInfo; ipv6: DbCollectionInfo; loading: string | null }
/**
 * A network device, e.g. "wlp3s0".
 */
export type Device = { 
/**
 * Name, e.g. "wlp3s0"
 */
name: string; 
/**
 * Note: for physical devices this is usually only on Windows.
 */
description: string | null; 
/**
 * If the device is up and running.
 */
ready: boolean; 
/**
 * If the device is a wireless device.
 */
wireless: boolean }
/**
 * Location metadata.
 */
export type Location = { city: string | null; region: string | null; country_code: string }
export type LookupInfo = { crd: Coordinate; loc: Location }
export type MovingAverageInfo = { total: number; avg_s: number }
/**
 * Fired any time the state of loaded or selected databases are changed on the backend.
 */
export type PcapStateChange = PcapStateInfo
export type PcapStateInfo = { Loaded: { version: string; devices: Device[]; capture: Device | null } } | { Unavailable: string }
export type TAURI_CHANNEL<TSend> = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
