// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A generalized lat/lon coordinate type which seeps all the way up the stack to leaflet's `LatLngExpression`.
 */
export type GenCoordinate<C> = { lat: C; lng: C };
