// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenCoordinate } from "./GenCoordinate";

export type Hop = { ip: string | null; coord: GenCoordinate<number> | null };
