// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionInfo } from "./ConnectionInfo";

export type CaptureStateInfo = { connections: Array<ConnectionInfo>, thread_id: string, };