// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A captured connection from the device/thread identified by `capturing_uuid`
 */
export type Connection = { thread_id: string, outgoing: boolean, ip: string, };