// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionDirection } from "./ConnectionDirection";

export type ConnectionInfo = {
  ip: string;
  size: number;
  direction: ConnectionDirection;
  current: boolean;
};
