// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatabaseInfo = {
  name: string;
  attribution_text: string | null;
  path: string | null;
  build_time: string;
  unique_locations: number;
  strings: number;
};
