// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A simplified RangeInclusive<Ipv4Addr/u32> for our TS api.
 */
export type IpRange = { lower: string; upper: string };
