// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Location = { latitude: number, longitude: number, city: string | null, country_code: string, };