// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpRange } from "./IpRange";
import type { Location } from "./Location";

/**
 * A location and its associated Ip Ranges
 */
export type LocationBlock = { location: Location, blocks: Array<IpRange>, };