[package]
name = "pcap-state"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
tracing.workspace = true
tauri-specta.workspace = true
tauri.workspace = true
dashmap.workspace = true
specta.workspace = true
tokio.workspace = true

pcap-dyn = { path = "../pcap-dyn" }

