[package]
name = "child-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
specta.workspace = true
thiserror.workspace = true
serde_json.workspace = true
base64 = "0.22.1"
