[package]
name = "trace"
version = "0.1.0"
edition = "2024"

[dependencies]
ip_rfc.workspace = true
ipgeo-state = { path = "../ipgeo-state" }
specta.workspace = true
serde.workspace = true
trippy-core = "0.13.0"
tauri.workspace = true
tracing.workspace = true
