
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Load in the databases from the disk cache.
 */
async refreshCache() : Promise<Result<DbStateInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:ipgeo|refresh_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a [`DatabaseSource`] from its origin.
 */
async downloadSource(source: DatabaseSource, nameResp: TAURI_CHANNEL<string>, progResp: TAURI_CHANNEL<number>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:ipgeo|download_source", { source, nameResp, progResp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unload the database, freeing up memory.
 */
async unloadDatabase(source: DatabaseSource) : Promise<void> {
    await TAURI_INVOKE("plugin:ipgeo|unload_database", { source });
},
/**
 * Set the given [`DatabaseSource`] as the selected database
 * for lookups on it's associated database type.
 */
async setSelectedDatabase(source: DatabaseSource) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:ipgeo|set_selected_database", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve the current [`DbStateInfo`] of the database.
 * 
 * This info is given out in [`DbStateChange`](super::DbStateChange),
 * but this is useful for getting it at page load, for example.
 */
async databaseState() : Promise<DbStateInfo> {
    return await TAURI_INVOKE("plugin:ipgeo|database_state");
},
/**
 * Lookup a given [`IpAddr`] in the currently selected database(s).
 */
async lookupIp(ip: string) : Promise<LookupInfo | null> {
    return await TAURI_INVOKE("plugin:ipgeo|lookup_ip", { ip });
},
/**
 * Get a hostname with the system for a given [`IpAddr`].
 */
async lookupDns(ip: string) : Promise<Result<string | null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:ipgeo|lookup_dns", { ip }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a hostname with the system for a given [`IpAddr`].
 */
async lookupHost(host: string) : Promise<Result<string | null, null>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:ipgeo|lookup_host", { host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Attempt to get the user's current [`LookupInfo`] from their IP address.
 */
async myLocation() : Promise<Result<LookupInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:ipgeo|my_location") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
dbStateChange: DbStateChange
}>({
dbStateChange: "plugin:ipgeo:db-state-change"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * A basic latitude/longitude pair.
 */
export type Coordinate = { 
/**
 * Latitude
 */
lat: number; 
/**
 * Longitude
 */
lng: number }
/**
 * Sources for where this database came from, as given to the user.
 * This allows us to de-duplicate common databases and download them
 * in-application.
 */
export type DatabaseSource = "dbipcombined" | "geolite2combined" | { file: string }
/**
 * Information about the loaded and selected databases in a [`DbSet`].
 */
export type DbSetInfo = { selected: DatabaseSource | null; loaded: DatabaseSource[] }
/**
 * Event fired whenever the state of loaded or selected databases changes.
 * 
 * Used to notify the frontend of updates to the database state.
 */
export type DbStateChange = DbStateInfo
/**
 * Summary of the loaded and selected databases for each IP type.
 */
export type DbStateInfo = { ipv4: DbSetInfo; ipv6: DbSetInfo; combined: DbSetInfo }
/**
 * A [`Coordinate`]'s associated city, region, and country.
 */
export type Location = { city: string | null; region: string | null; countryCode: string }
/**
 * A [`Coordinate`]/[`Location`] pair.
 */
export type LookupInfo = { crd: Coordinate; loc: Location }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}